# Generated by Django 6.0.1 on 2026-01-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.route'),
        ),
    ]
