# Generated by Django 6.0.1 on 2026-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_str',
            field=models.CharField(default='', max_length=200),
        ),
    ]
