# Generated by Django 6.0.1 on 2026-01-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_route_route_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route_id',
        ),
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='transport.bus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='path',
            field=models.JSONField(),
        ),
    ]
