# Generated by Django 6.0.1 on 2026-01-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_remove_bus_route_id_route_bus_alter_route_path'),
        ('users', '0003_user_phone_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='users.driver'),
        ),
    ]
