# Generated by Django 6.0.1 on 2026-02-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_bus_driver_id'),
        ('users', '0004_rename_bus_id_student_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='users.driver'),
        ),
    ]
